---
- name: Install NodeJs
  yum:
    name: nodejs
    state: present
    update_cache: yes

- name: Install NPM
  yum:
    name: npm
    state: present
    update_cache: yes

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes
    state: present

# - name: Install Node App Dependencies
#   command: npm install
#   args:
#     chdir: /home/ec2-user/sample_todo
#   notify: Run the node app
