name: Destroying Infrastructure
run-name: Destroying the Infrastructure

on:
  workflow_dispatch:
  push:
    branches = ["INTERN-77-"]

jobs:
  destroy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Terraform Destroy
        run: terraform destroy -var-file=./dev.tfvars -auto-approve
        working-directory: Terraform
